### ISSUE TITLE
Uncaught OutOfMemoryError in HTTPClient.upload

### ISSUE THREAD

**Issue by tadfisher** [segmentio/analytics-kotlin#28] opened 2021-08-30 17:27 UTC
**Describe the bug**
HTTPUrlConnection allocates strings internally, which can cause an OOM that isn't caught in Segment.

```
java.lang.OutOfMemoryError: Failed to allocate a 40 byte allocation with 8 free bytes and 8B until OOM, target footprint 268435456, growth limit 268435456
        at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
        at java.lang.StringBuilder.toString(StringBuilder.java:413)
        at com.android.okhttp.internal.http.RequestLine.get(RequestLine.java:33)
        at com.android.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:258)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
        at com.segment.analytics.kotlin.core.HTTPClient.upload(HTTPClient.kt:6)
        at com.segment.analytics.kotlin.core.SegmentDestination$flush$$inlined$run$lambda$1.invokeSuspend(SegmentDestination.kt:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:2)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:18)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:10)
```

**Platform (please complete the following information):**
 - Library Version in use: 1.2.0
 - Platform being tested: Android (Google Pixel 4, API 30)
 - Integrations in use: None

**Comment by wenxi-zeng** [comment] 2021-08-30 20:08
hi @tadfisher thanks for bring this to our attention. we will do a memory profiling to check if there is memory leak in side our SDK. 

in the meanwhile, you can use `android:largeHeap="true"` to temporary unblock from this issue. but be caution that this does not solve the problem, but rather let the memory increase freely.


it'd be great that if you could do a test on your end with
```kotlin
configuration.autoAddSegmentDestination = false
```
and see if OOM still happens. this helps us determine if the OOM is actually caused by network requests.


it'd also be great if you could help answer the following:
* approximately, how many track/identify/green/group calls are made per minute? and what's the settings you used for `flushAt` and `flushInterval`? this helps us to reproduce the situation you encountered.
* does the issue happens every time an upload happened? or rather it happens after the app being used for a while? if so:
  * how long do you have to wait for this to happen?
  * can you reboot your device and test again see if this still happens?

**Comment by wenxi-zeng** [comment] 2021-09-13 16:25
@tadfisher we did a memory profiling and found there is no memory leak in the SDK. however, it's possible that the SDK causes a high memory usage if the configuration is not optimal and the event data flow is very intensive (100+ events per second). we are making a change to optimize the default configuration. for the meanwhile, we recommend the following:
* set `configuration.ioDispatcher` to be a fixed number threads, for example `Executors.newFixedThreadPool(2)
        .asCoroutineDispatcher()`. the less the threads, the better memory usage. but should be at least 2 threads

we also recommend a memory profiling on the app, since normal use case is unlikely to cause the issue we observed. I'm closing this issue out as we have a conclusion that the OOM issue does not lie on SDK, but if you're still experiencing the same issue with the recommended configuration, feel free to reopen this issue and provide more context.

**Closed by wenxi-zeng** 2021-09-13 16:25 UTC
